version: "3.7"

services: 
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  user:
    build:
      context: ./user/.
    restart: always
    env_file: user/.env
    environment: 
      - DATABASE_HOST=user-database
      - DATABASE_SYNC=true
      - DATABASE_LOGGING=true
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=Host(`user.localhost`)"
      - "traefik.http.routers.user.entrypoints=web"
      - "traefik.http.middlewares.latency-check.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - 5672:5672
      - 15672:15672

  account:
    build: 
      context: ./account/.
    restart: always
    env_file: account/.env
    environment: 
      - DATABASE_HOST=account-database
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`account.localhost`)"
      - "traefik.http.routers.account.entrypoints=web"
      - "traefik.http.middlewares.latency-check.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"

  profile:
    build: 
      context: ./profile/.
    restart: always
    env_file: profile/.env
    environment: 
      - DATABASE_HOST=profile-database
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.profile.rule=Host(`profile.localhost`)"
      - "traefik.http.routers.profile.entrypoints=web"
      - "traefik.http.middlewares.latency-check.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"

  file:
    build: 
      context: ./file/.
    restart: always
    env_file: file/.env
    environment: 
      - DATABASE_HOST=file-database
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.file.rule=Host(`file.localhost`)"
      - "traefik.http.routers.file.entrypoints=web"
      - "traefik.http.middlewares.latency-check.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"

  redis-master:
    image: kyhsa93/redis-master
    restart: always

  redis-slave:
    image: kyhsa93/redis-slave
    restart: always

  user-database:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment: 
      - MYSQL_DATABASE=user
    volumes: 
      - ~/database/msa-example/user:/var/lib/mysql

  account-database:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment: 
      - MYSQL_DATABASE=account
    volumes: 
      - ~/database/msa-example/account:/var/lib/mysql

  profile-database:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment: 
      - MYSQL_DATABASE=profile
    volumes: 
      - ~/database/msa-example/profile:/var/lib/mysql

  file-database:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment: 
      - MYSQL_DATABASE=file
    volumes: 
      - ~/database/msa-example/file:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports: 
      - 4572:4572
    environment: 
      - SERVICE-s3
    volumes: 
      - ./.aws:/docker-entrypoint-initaws.d
