apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nestjs-rest-cqrs-example.fullname" . }}
  labels:
    app: nestjs-rest-cqrs-example
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nestjs-rest-cqrs-example
  template:
    metadata:
      labels:
        app: nestjs-rest-cqrs-example
    spec:
      containers:
        - name: nestjs-rest-cqrs-example
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_HOST
              value: "database"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:5.7
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: nest
            - name: MYSQL_ROOT_PASSWORD
              value: test
