apiVersion: v1
kind: Service
metadata:
  name: {{ include "nestjs-rest-cqrs-example.fullname" . }}
  labels:
    app: nestjs-rest-cqrs-example
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: nestjs-rest-cqrs-example
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: database
